[package]
name = "process_supervisor"
version = "0.1.0"
authors = ["Marco Dell'Olio <dellolio.marco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
